# -- 코드를 입력하세요
SELECT R.CAR_ID, R.CAR_TYPE, ROUND(R.DAILY_FEE * 30 * (100-DD.DISCOUNT_RATE) / 100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR R
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DD ON R.CAR_TYPE=DD.CAR_TYPE
WHERE R.CAR_TYPE IN ("세단", "SUV") 
AND DD.DURATION_TYPE="30일 이상" 
AND R.CAR_ID NOT IN (SELECT CAR_ID
                     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                     WHERE 
    START_DATE BETWEEN '2022-11-01' AND '2022-11-30'
    OR
    END_DATE BETWEEN '2022-11-01' AND '2022-11-30'
    OR
    '2022-11-01' BETWEEN START_DATE AND END_DATE
    OR
    '2022-11-30' BETWEEN START_DATE AND END_DATE
)
GROUP BY R.CAR_ID
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;

# SELECT R.CAR_ID, R.CAR_TYPE, DATEDIFF(END_DATE, START_DATE)*ROUND(DAILY_FEE*(100-(SELECT DISCOUNT_RATE
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN DD
# JOIN CAR_RENTAL_COMPANY_CAR RR ON RR.CAR_TYPE=DD.CAR_TYPE
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CC ON CC.CAR_ID=RR.CAR_ID
# WHERE DATEDIFF(END_DATE, START_DATE) >= REGEXP_REPLACE(DURATION_TYPE, '[가-힣]', '' ) AND ('2022-11-01'<=END_DATE AND '2022-11-30'>START_DATE)AND R.CAR_ID=RR.CAR_ID GROUP BY R.CAR_ID))/100) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR R
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON H.CAR_ID=R.CAR_ID
# WHERE R.CAR_TYPE IN ('세단', 'SUV')
# GROUP BY CAR_ID
# ORDER BY FEE DESC, R.CAR_TYPE, R.CAR_ID DESC
# HAVING 

# SELECT DISCOUNT_RATE, END_DATE
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN DD
# JOIN CAR_RENTAL_COMPANY_CAR RR ON RR.CAR_TYPE=DD.CAR_TYPE
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CC ON CC.CAR_ID=RR.CAR_ID
# WHERE DATEDIFF(END_DATE, START_DATE) >= REGEXP_REPLACE(DURATION_TYPE, '[가-힣]', '' ) AND ('2022-11-01'<=END_DATE AND '2022-11-30'>START_DATE)


