-- 코드를 입력하세요
SELECT Y.FOOD_TYPE, Y.REST_ID, Y.REST_NAME, Y.FAVORITES
FROM (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
      FROM REST_INFO
      GROUP BY FOOD_TYPE) AS X
INNER JOIN REST_INFO AS Y ON X.FOOD_TYPE = Y.FOOD_TYPE AND FAVORITES=MAX_FAVORITES
ORDER BY FOOD_TYPE DESC