-- 코드를 입력하세요
SELECT DATE_FORMAT(START_DATE, "%c") AS DATE, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, "%m") in ("08", "09", "10") AND CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, "%m") in ("08", "09", "10")
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)
GROUP BY DATE, CAR_ID
ORDER BY CAST(DATE AS UNSIGNED), CAR_ID DESC;
