-- 코드를 입력하세요
WITH RECURSIVE TIME AS (
SELECT 0 AS HOUR
    
UNION ALL
    
SELECT HOUR+1
FROM TIME
WHERE HOUR<23)

SELECT TIME.HOUR, COUNT(ANIMAL_OUTS.DATETIME) AS COUNT
FROM TIME
LEFT JOIN ANIMAL_OUTS ON TIME.HOUR=HOUR(ANIMAL_OUTS.DATETIME) 
GROUP BY HOUR
ORDER BY HOUR
