-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) as "전체 주소", CONCAT_WS("-", "010" , SUBSTR(TLNO, 4, 4), SUBSTR(TLNO, 8, 4)) as "전화번호"
FROM USED_GOODS_USER
LEFT JOIN USED_GOODS_BOARD ON USER_ID = WRITER_ID 
GROUP BY USER_ID
HAVING COUNT(WRITER_ID) > 2
ORDER BY USER_ID DESC