-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(USED_GOODS_BOARD.PRICE) as TOTAL_SALED
FROM USED_GOODS_USER
LEFT JOIN USED_GOODS_BOARD ON USER_ID = WRITER_ID
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID HAVING TOTAL_SALED >= 700000
ORDER BY TOTAL_SALED