-- 코드를 입력하세요

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE M
RIGHT JOIN REST_REVIEW R ON R.MEMBER_ID=M.MEMBER_ID
WHERE M.MEMBER_ID IN (SELECT B.MEMBER_ID 
                      FROM REST_REVIEW B
                      GROUP BY B.MEMBER_ID HAVING COUNT(*) IN (SELECT MAX(CNT) FROM (SELECT A.MEMBER_ID, COUNT(REVIEW_ID) AS CNT
                       FROM REST_REVIEW AS A
                       GROUP BY A.MEMBER_ID
                       ORDER BY CNT DESC
                        LIMIT 1) AS C))
ORDER BY REVIEW_DATE, REVIEW_TEXT
