-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK
INNER JOIN BOOK_SALES ON BOOK_SALES.BOOK_ID=BOOK.BOOK_ID
WHERE '2022-01'=DATE_FORMAT(SALES_DATE, '%Y-%m')
GROUP BY CATEGORY
ORDER BY CATEGORY

# SELECT CATEGORY, (SELECT SALES FROM BOOK_SALES GROUP BY BOOK_ID) AS TOTAL_SALES
# FROM BOOK
# GROUP BY CATEGORY
# ORDER BY CATEGORY
# SELECT SALES 
# FROM BOOK_SALES 
# WHERE '2022-01'=DATE_FORMAT(SALES_DATE, '%Y-%m')
# GROUP BY BOOK_SALES.BOOK_ID