-- 코드를 입력하세요
SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE*SALES) AS TOTAL_SALES
FROM BOOK AS B
LEFT JOIN AUTHOR AS A ON B.AUTHOR_ID=A.AUTHOR_ID
LEFT JOIN BOOK_SALES AS S ON S.BOOK_ID=B.BOOK_ID
WHERE '2022-01'=DATE_FORMAT(SALES_DATE, '%Y-%m')
GROUP BY B.AUTHOR_ID, CATEGORY
ORDER BY B.AUTHOR_ID ASC, CATEGORY DESC;