-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, PATIENT.PT_NO, DOCTOR.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT
LEFT JOIN PATIENT ON PATIENT.PT_NO=APPOINTMENT.PT_NO
LEFT JOIN DOCTOR ON MDDR_ID=DR_ID
WHERE '2022-04-13'=DATE_FORMAT(APNT_YMD, "%Y-%m-%d") AND APNT_CNCL_YN='N' AND DOCTOR.MCDP_CD='CS'
ORDER BY APNT_YMD